<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class establishmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $establishments = array(
            array('id' => '1','university_id' => '27','ar_name' => 'المعهدالعالي للفن المسرحي بتونس','fr_name' => 'INSTITUT SUPERIEUR D\'ART DRAMATIQUE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','university_id' => '27','ar_name' => 'المعهد العالي للدراسات التطبيقية في الإنسانيات بتونس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','university_id' => '27','ar_name' => 'المعهد العالى لمهن التراث بتونس','fr_name' => 'INSTITUT SUPERIEUR DES METIERS DU  PATRIMOINE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','university_id' => '27','ar_name' => 'كلية العلوم الإنسانية والاجتماعية بتونس','fr_name' => 'FACULTE DES SCIENCES HUMAINES & SOCIALES DE T','created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','university_id' => '27','ar_name' => 'المدرسة العليا للعلوم الإقتصادية والتجارية بتونس','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES ECONOMIQUES & C','created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','university_id' => '27','ar_name' => 'المعهد العالي للأعمال بتونس','fr_name' => 'TUNIS BUSINESS SCHOOL','created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','university_id' => '27','ar_name' => 'المعهد التحضيري للدراسات الهندسية بتونس','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','university_id' => '27','ar_name' => 'المعهد العالي للتنشيط الشبابي والثقافي ببئر الباي','fr_name' => 'INSTITUT SUPERIEUR DE L\'ANIMATION POUR LA JEU','created_at' => NULL,'updated_at' => NULL),
            array('id' => '9','university_id' => '27','ar_name' => 'المعهد العالى للفنون الجميلة بتونس','fr_name' => 'INSTITUT SUPERIEUR DES BEAUX-ARTS DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','university_id' => '27','ar_name' => 'المعهد العالي للتصرف بتونس','fr_name' => 'INSTITUT SUPERIEUR DE GESTION DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','university_id' => '27','ar_name' => 'المعهد العالي للموسيقى بتونس','fr_name' => 'INSTITUT SUPERIEUR DE MUSIQUE DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','university_id' => '28','ar_name' => 'كلية الآداب والفنون والإنسانيات بمنوبة','fr_name' => 'FACULTE DES LETTRES, DES ARTS & DES HUMANITES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','university_id' => '28','ar_name' => 'المعهد العالي للرياضة والتربية البدنية بقصر السعيد','fr_name' => 'INSTITUT SUPERIEUR DU SPORT & DE L\'EDUCATION ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '14','university_id' => '28','ar_name' => 'المعهد العالي لفنون الملتميديا بمنوبة','fr_name' => 'INSTITUT SUPERIEUR DES  ARTS DU MULTIMEDIA DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '15','university_id' => '28','ar_name' => 'المدرسة الوطنية للطب البيطري بسيدي ثابت','fr_name' => 'ECOLE NATIONALE DE MEDECINE VETERINAIRE DE SI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '16','university_id' => '28','ar_name' => 'معهد الصحافة وعلوم الإخبار','fr_name' => 'INSTITUT DE PRESSE & DES SCIENCES DE L\'INFORM','created_at' => NULL,'updated_at' => NULL),
            array('id' => '17','university_id' => '28','ar_name' => 'المدرسة العليا للتجارة بتونس','fr_name' => 'ECOLE SUPERIEURE DE COMMERCE DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '18','university_id' => '28','ar_name' => 'المدرسة الوطنيّة لعلوم الإعلاميّة','fr_name' => 'ECOLE NATIONALE DES SCIENCES DE L\'INFORMATIQU','created_at' => NULL,'updated_at' => NULL),
            array('id' => '19','university_id' => '28','ar_name' => 'المدرسة العليا لعلوم وتكنولوجيات التصميم','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNOLOGIES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '20','university_id' => '28','ar_name' => 'المدرسة العليا للإقتصاد الرقمي بمنوبة','fr_name' => 'ECOLE SUPERIEURE DE L\'ECONOMIE NUMERIQUE DE L','created_at' => NULL,'updated_at' => NULL),
            array('id' => '21','university_id' => '28','ar_name' => 'المعهد العالي للمحاسبة وإدارة المؤسسات','fr_name' => 'INSTITUT SUPERIEUR DE COMPTABILITE & D\'ADMINI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '22','university_id' => '28','ar_name' => 'المعهد العالي للتربية المختصة','fr_name' => 'INSTITUT SUPERIEUR DE L\'EDUCATION SPECIALISÉE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '23','university_id' => '28','ar_name' => 'المعهد العالي للتوثيق بتونس','fr_name' => 'INSTITUT SUPERIEUR DE DOCUMENTATION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '24','university_id' => '28','ar_name' => 'المعهد العالي للبيوتكنولوجيا بسيدي ثابت','fr_name' => 'INSTITUT SUPERIEUR DE BIOTECHNOLOGIE DE SIDI ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '25','university_id' => '29','ar_name' => 'المعهد العالي للتكنولوجيات الطبية بتونس','fr_name' => 'INSTITUT SUPERIEUR DES TECHNOLOGIES MEDICALES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '26','university_id' => '29','ar_name' => 'معهد بورقيبة للغات الحية','fr_name' => 'INSTITUT BOURGUIBA DES LANGUES VIVANTES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '27','university_id' => '29','ar_name' => 'المعهد العالي للإعلامية','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE A L\'ARIANA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '28','university_id' => '29','ar_name' => 'كلية الحقوق والعلوم السياسية بتونس','fr_name' => 'FACULTE DE DROIT & DES SCIENCES POLITIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '29','university_id' => '29','ar_name' => 'كلية العلوم للرياضيات والفيزياء والطبيعيات بتونس','fr_name' => 'FACULTE DES SCIENCES MATHEMATIQUES, PHYSIQUES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '30','university_id' => '29','ar_name' => 'المعهد التحضيري للدراسات الهندسية بالمنار','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '31','university_id' => '29','ar_name' => 'المعهد العالي للعلوم الإنسانية بتونس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES HUMAINES DE T','created_at' => NULL,'updated_at' => NULL),
            array('id' => '32','university_id' => '29','ar_name' => 'المعهد العالي للعلوم البيولوجية التطبيقية بتونس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES BIOLOGIQUES A','created_at' => NULL,'updated_at' => NULL),
            array('id' => '33','university_id' => '29','ar_name' => 'كلية الطب بتونس','fr_name' => 'FACULTE DE MEDECINE DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '34','university_id' => '29','ar_name' => 'كلية العلوم الإقتصادية والتصرف بتونس','fr_name' => 'FACULTE DES SCIENCES  ECONOMIQUES & DE GESTIO','created_at' => NULL,'updated_at' => NULL),
            array('id' => '35','university_id' => '29','ar_name' => 'المعهد العالي لعلوم التمريض بتونس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES INFIRMIERES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '36','university_id' => '29','ar_name' => 'المدرسة العليا لعلوم وتقنيات الصحة بتونس','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '37','university_id' => '30','ar_name' => 'المعهد الوطني للعلوم التطبيقية والتكنولوجيا','fr_name' => 'INSTITUT NATIONAL DES SCIENCES APPLIQUEES & D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '38','university_id' => '30','ar_name' => 'المعهد التحضيري للدراسات العلمية والتقنية','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES SCIENTIFIQUE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '39','university_id' => '30','ar_name' => 'المعهد العالي للغات بتونس','fr_name' => 'INSTITUT SUPERIEUR  DES LANGUES DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '40','university_id' => '30','ar_name' => 'كلية العلوم الإقتصادية والتصرف بنابل','fr_name' => 'FACULTE DES SCIENCES ECONOMIQUES & DE GESTION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '41','university_id' => '30','ar_name' => 'المدرسة العليا للفلاحة بماطر','fr_name' => 'ECOLE SUPERIEURE  D\'AGRICULTURE DE MATEUR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '42','university_id' => '30','ar_name' => 'المدرسة العليا للفلاحة بمقرن','fr_name' => 'ECOLE SUPERIEURE  D\'AGRICULTURE DE MOGRANE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '43','university_id' => '30','ar_name' => 'المدرسة التونسية للتقنيات','fr_name' => 'ECOLE POLYTECHNIQUE DE TUNISIE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '44','university_id' => '30','ar_name' => 'المعهد الوطني للعلوم الفلاحية بتونس','fr_name' => 'INSTITUT NATIONAL AGRONOMIQUE DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '45','university_id' => '30','ar_name' => 'المعهد العالى للدراسات التحضيرية في البيولوجيا والجولوجيا بسكرة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES PREPARATOIRES E','created_at' => NULL,'updated_at' => NULL),
            array('id' => '46','university_id' => '30','ar_name' => 'المدرسة العليا للمواصلات بتونس','fr_name' => 'ECOLE SUPERIEURE DES COMMUNICATIONS DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '47','university_id' => '30','ar_name' => 'المعهد العالي لإطارات الطفولة','fr_name' => 'INSTITUT SUPERIEUR DES CADRES DE L\'ENFANCE DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '48','university_id' => '30','ar_name' => 'المدرسة العليا للسمعي البصري والسينما بقمرت','fr_name' => 'ECOLE SUPERIEUR DE L\'AUDIO-VISUEL & DU CINEMA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '49','university_id' => '30','ar_name' => 'المدرسة العليا للإحصاء وتحليل المعلومات','fr_name' => 'ECOLE SUPERIEURE DE LA STATISTIQUE & DE L\'ANA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '50','university_id' => '30','ar_name' => 'المدرسة الوطنية للمهندسين بقرطاج','fr_name' => 'ECOLE SUPERIEURE DE TECHNOLOGIE & D\'INFORMATI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '51','university_id' => '30','ar_name' => 'معهد الدراسات العليا التجارية بقرطاج','fr_name' => 'INSTITUT DES HAUTES ETUDES COMMERCIALES DE CA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '52','university_id' => '30','ar_name' => 'المعهد التحضيري للدراسات الهندسية بنابل','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '53','university_id' => '30','ar_name' => 'المعهد العالي لعلوم وتكنولوجيات البيئة ببرج السدرية','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES & TCHNOLOGIES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '54','university_id' => '30','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بماطر','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '55','university_id' => '30','ar_name' => 'كلية العلوم ببنزرت','fr_name' => 'FACULTE DES SCIENCES DE BIZERTE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '56','university_id' => '30','ar_name' => 'المدرسة العليا للصناعات الغذائية بتونس','fr_name' => 'ECOLE SUPERIEURE D\'INDUSTRIES ALIMENTAIRES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '57','university_id' => '30','ar_name' => 'المدرسة الوطنية للمهندسين ببنزرت','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE BIZERTE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '58','university_id' => '30','ar_name' => 'المعهد العالي للصيد البحري وتربية الأحياء المائية ببنزرت','fr_name' => 'INSTITUT SUPERIEUR DE PECHE & D\'AQUACULTURE D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '59','university_id' => '30','ar_name' => 'المعهد الوطني للشغل والدراسات الإجتماعية بتونس','fr_name' => 'INSTITUT NATIONAL DU TRAVAIL & DES ETUDES SOC','created_at' => NULL,'updated_at' => NULL),
            array('id' => '60','university_id' => '30','ar_name' => 'معهد الدراسات السياحية العليا بسيدي الظريف','fr_name' => 'INSTITUT DES HAUTES ETUDES TOURISTIQUES DE SI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '61','university_id' => '30','ar_name' => 'المعهد العالى للفنون الجميلة بنابل','fr_name' => 'INSTITUT SUPERIEUR DES BEAUX-ARTS DE NABEUL','created_at' => NULL,'updated_at' => NULL),
            array('id' => '62','university_id' => '30','ar_name' => 'المدرسة الوطنية للعلوم والتكنولوجيات المتقدمة ببرج السدرية','fr_name' => 'ECOLE NATIONALE DES SCIENCES ET TECHNOLOGIES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '63','university_id' => '30','ar_name' => 'المعهد العالي للغات بنابل','fr_name' => 'INSTITUT SUPERIEUR DES LANGUES DE NABEUL','created_at' => NULL,'updated_at' => NULL),
            array('id' => '64','university_id' => '30','ar_name' => 'المعهد العالي لتكنولوجيات البيئة والعمران والبنيان','fr_name' => 'INSTITUT SUPERIEUR DES TECHNOLOGIES DE L\'ENVI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '65','university_id' => '30','ar_name' => 'المعهد التحضيري للدراسات الهندسية ببنزرت','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '66','university_id' => '30','ar_name' => 'كلية العلوم القانونية والسياسية والإجتماعية بتونس','fr_name' => 'FACULTE DES SCIENCES JURIDIQUES, POLITIQUES &','created_at' => NULL,'updated_at' => NULL),
            array('id' => '67','university_id' => '30','ar_name' => 'المعهد العالي لتكنولوجيات المعلومات والإتصال ببرج السدرية','fr_name' => 'INSTITUT SUPERIEUR DES TECHNOLOGIES DE L\'INFO','created_at' => NULL,'updated_at' => NULL),
            array('id' => '68','university_id' => '30','ar_name' => 'المعهد العالي للتصرف ببنزرت','fr_name' => 'INSTITUT SUPERIEUR DE GESTION BIZERTE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '69','university_id' => '31','ar_name' => 'المعهد العالي لأصول الدين بتونس','fr_name' => 'INSTITUT SUPERIEUR DE THEOLOGIE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '70','university_id' => '31','ar_name' => 'المعهد العالي للحضارة الإسلامية بتونس','fr_name' => 'INSTITUT SUPERIEUR DE LA CIVILISATION ISLAMIQ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '71','university_id' => '31','ar_name' => 'مركز الدراسات الإسلامية بالقيروان','fr_name' => 'CENTRE D\'ETUDES ISLAMIQUES DE KAIROUAN','created_at' => NULL,'updated_at' => NULL),
            array('id' => '72','university_id' => '32','ar_name' => 'المدرسة الوطنية للمهندسين بسوسة','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE SOUSSE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '73','university_id' => '32','ar_name' => 'معهد الدراسات العليا التجارية بسوسة','fr_name' => 'INSTITUT DES HAUTES ETUDES COMMERCIALES DE SO','created_at' => NULL,'updated_at' => NULL),
            array('id' => '74','university_id' => '32','ar_name' => 'المعهد العالى للفنون الجميلة بسوسة','fr_name' => 'INSTITUT SUPERIEUR DES BEAUX-ARTS DE SOUSSE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '75','university_id' => '32','ar_name' => 'المعهد العالى للتصرف بسوسة','fr_name' => 'INSTITUT SUPERIEUR DE GESTION DE SOUSSE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '76','university_id' => '32','ar_name' => 'المعهد العالي للموسيقى بسوسة','fr_name' => 'INSTITUT SUPERIEUR DE MUSIQUE DE SOUSSE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '77','university_id' => '32','ar_name' => 'المدرسة العليا للعلوم والتكنولوجيا بحمام سوسة','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNOLOGIE D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '78','university_id' => '32','ar_name' => 'المعهد العالي للمالية والجباية بسوسة','fr_name' => 'INSTITUT SUPERIEUR DES FINANCES & DE FISCALIT','created_at' => NULL,'updated_at' => NULL),
            array('id' => '79','university_id' => '32','ar_name' => 'المعهد العالي للإعلامية وتقنيات الاتصال بحمام سوسة','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE & DES TECHN','created_at' => NULL,'updated_at' => NULL),
            array('id' => '80','university_id' => '32','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بسوسة','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '81','university_id' => '32','ar_name' => 'المعهد العالي للنقل وخدمات الاتصال بسوسة','fr_name' => 'INSTITUT SUPERIEUR DU TRANSPORT & DE LA LOGIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '82','university_id' => '32','ar_name' => 'كلية العلوم الاقتصادية والتصرف بسوسة','fr_name' => 'FACULTE DES SCIENCES ECONOMIQUES ET DE GESTIO','created_at' => NULL,'updated_at' => NULL),
            array('id' => '83','university_id' => '32','ar_name' => 'كلية الآداب والعلوم الإنسانية بسوسة','fr_name' => 'FACULTE DES LETTRES & DES SCIENCES HUMAINES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '84','university_id' => '32','ar_name' => 'المعهد العالي للعلوم الفلاحية بشط مريم','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES AGRICOLES DE ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '85','university_id' => '32','ar_name' => 'كلية الطب بسوسة','fr_name' => 'FACULTE DE MEDECINE DE SOUSSE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '86','university_id' => '32','ar_name' => 'المعهد العالي لعلوم التمريض بسوسة','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES INFIRMIERES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '87','university_id' => '32','ar_name' => 'المدرسة العليا لعلوم وتقنيات الصحة بسوسة','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '88','university_id' => '33','ar_name' => 'المدرسة الوطنية للمهندسين بصفاقس','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '89','university_id' => '33','ar_name' => 'المعهد العالي لإدارة الأعمال بصفاقس','fr_name' => 'INSTITUT SUPERIEUR  D\'ADMINISTRATION DES AFFA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '90','university_id' => '33','ar_name' => 'المعهد العالي للبيوتكنولوجيا بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DE BIOTECHNOLOGIE DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '91','university_id' => '33','ar_name' => 'المعهد العالي للتصرف الصناعي بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DE GESTION INDUSTRIELLE DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '92','university_id' => '33','ar_name' => 'المعهد العالي للموسيقى بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DE MUSIQUE DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '93','university_id' => '33','ar_name' => 'كلية الآداب والعلوم الإنسانية بصفاقس','fr_name' => 'FACULTE DES LETTRES & DES SCIENCES HUMAINES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '94','university_id' => '33','ar_name' => 'كلية العلوم الإقتصادية والتصرف بصفاقس','fr_name' => 'FACULTE DES SCIENCES ECONOMIQUES & DE GESTION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '95','university_id' => '33','ar_name' => 'المعهد العالي لعلوم التمريض بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES INFIRMIERES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '96','university_id' => '33','ar_name' => 'المعهد العالي للرياضة والتربية البدنية بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DU SPORT ET DE L\'EDUCATION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '97','university_id' => '33','ar_name' => 'المدرسة العليا للتجارة بصفاقس','fr_name' => 'ECOLE SUPERIEURE DE COMMERCE DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '98','university_id' => '33','ar_name' => 'المعهد التحضيري للدراسات الهندسية بصفاقس','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '99','university_id' => '33','ar_name' => 'المعهد العالى للفنون والحرف بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DES ARTS ET METIERS DE SFA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '100','university_id' => '33','ar_name' => 'المعهد العالي للإعلامية والملتميديا بصفاقس','fr_name' => 'INSTITUT SUPERIEUR  D\'NFORMATIQUE ET DU MULTI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '101','university_id' => '33','ar_name' => 'كلية الحقوق بصفاقس','fr_name' => 'FACULTE DE DROIT DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '102','university_id' => '33','ar_name' => 'كلية الطب بصفاقس','fr_name' => 'FACULTE DE MEDECINE DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '103','university_id' => '33','ar_name' => 'كلية العلوم بصفاقس','fr_name' => 'FACULTE DES SCIENCES DE SFAX','created_at' => NULL,'updated_at' => NULL),
            array('id' => '104','university_id' => '33','ar_name' => 'المدرسة العليا لعلوم وتقنيات الصحة بصفاقس','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '105','university_id' => '33','ar_name' => 'معهد الدراسات العليا التجارية بصفاقس','fr_name' => 'INSTITUT DES HAUTES ETUDES COMMERCIALES DE SF','created_at' => NULL,'updated_at' => NULL),
            array('id' => '106','university_id' => '34','ar_name' => 'المعهد العالي للغابات والمراعي الغابية بطبرقة','fr_name' => 'INSTITUT SYLVO-PASTORAL DE TABARKA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '107','university_id' => '34','ar_name' => 'المعهد العالي للدراسات التطبيقية في الإنسانيات بالكاف','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '108','university_id' => '34','ar_name' => 'المعهد العالي للموسيقى والمسرح بالكاف','fr_name' => 'INSTITUT SUPERIEUR DE MUSIQUE & DE THEATRE DU','created_at' => NULL,'updated_at' => NULL),
            array('id' => '109','university_id' => '34','ar_name' => 'المعهد العالي للفنون والحرف بسليانة','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE SILI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '110','university_id' => '34','ar_name' => 'المعهد العالي للإعلامية بالكاف','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE DU KEF','created_at' => NULL,'updated_at' => NULL),
            array('id' => '111','university_id' => '34','ar_name' => 'المدرسة العليا للفلاحة بالكاف','fr_name' => 'ECOLE SUPERIEURE D\'AGRICULTURE DU KEF','created_at' => NULL,'updated_at' => NULL),
            array('id' => '112','university_id' => '34','ar_name' => 'المعهد العالي لعلوم التمريض بالكاف','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES INFIRMIERES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '113','university_id' => '34','ar_name' => 'المعهد العالي للغات التطبيقية والاعلامية بباجة','fr_name' => 'INSTITUT SUPERIEUR DES LANGUES APPLIQUEES & D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '114','university_id' => '34','ar_name' => 'المعهد العالي للبيوتكنولوجيا بباجة','fr_name' => 'INSTITUT SUPERIEUR DE BIOTECHNOLOGIE DE BEJA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '115','university_id' => '34','ar_name' => 'كلية العلوم القانونية والإقتصادية والتصرف بجندوبة','fr_name' => 'FACULTE DES SCIENCES ECONOMIQUES & DE GESTION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '116','university_id' => '34','ar_name' => 'المعهد العالي للرياضة والتربية البدنية بالكاف','fr_name' => 'INSTITUT SUPERIEUR DU SPORT & DE L\'EDUCATION ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '117','university_id' => '35','ar_name' => 'المعهد العالي للتصرف بقابس','fr_name' => 'INSTITUT SUPERIEUR DE GESTION DE GABES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '118','university_id' => '35','ar_name' => 'المعهد العالي للفنون والحرف بقابس','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE GABE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '119','university_id' => '35','ar_name' => 'المعهد العالي للدراسات القانونية بقابس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES JURIDIQUES DE G','created_at' => NULL,'updated_at' => NULL),
            array('id' => '120','university_id' => '35','ar_name' => 'المعهد العالي للبيولوجيا التطبيقية بمدنين','fr_name' => 'INSTITUT SUPERIEURE DE BIOLOGIE APPLIQUEE DE ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '121','university_id' => '35','ar_name' => 'المعهد العالي لعلوم وتقنيات المياه بقابس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES & TECHNIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '122','university_id' => '35','ar_name' => 'المعهد العالي للعلوم الإنسانية بمدنين','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES HUMAINES DE M','created_at' => NULL,'updated_at' => NULL),
            array('id' => '123','university_id' => '35','ar_name' => 'المعهد العالي للمنظومات الصناعية بقابس','fr_name' => 'INSTITUT SUPERIEUR DES SYSTEMES INDUSTRIELS D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '124','university_id' => '35','ar_name' => 'المعهد العالي للإعلامية بمدنين','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE DE MEDENINE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '125','university_id' => '35','ar_name' => 'المدرسة الوطنية للمهندسين بقابس','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE GABES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '126','university_id' => '35','ar_name' => 'المعهد العالي للغات بقابس','fr_name' => 'INSTITUT SUPERIEUR  DES LANGUES DE GABES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '127','university_id' => '35','ar_name' => 'كلية العلوم بقابس','fr_name' => 'FACULTE DES SCIENCES DE GABES','created_at' => NULL,'updated_at' => NULL),
            array('id' => '128','university_id' => '35','ar_name' => 'المعهد العالي لعلوم التمريض بقابس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES INFIRMIERES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '129','university_id' => '35','ar_name' => 'المعهد العالي للإعلامية والملتيميديا بقابس','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE & DU MULTIM','created_at' => NULL,'updated_at' => NULL),
            array('id' => '130','university_id' => '35','ar_name' => 'المعهد العالي للفنون والحرف بتطاوين','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE TATA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '131','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بنابل','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '132','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بصفاقس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '133','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بالكاف','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '134','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بسليانة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '135','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بسيدي بوزيد','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '136','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بتوزر','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '137','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بمدنين','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '138','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بتطاوين','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '139','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '140','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بالشرقية','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '141','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية برادس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '142','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بقفصة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '143','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بجربة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '144','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بقصر هلال','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '145','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بقابس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '146','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بجندوبة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '147','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بالمهدية','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '148','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية ببنزرت','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '149','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بسوسة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '150','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بزغوان','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '151','university_id' => '36','ar_name' => 'المعهد العالى للدراسات التكنولوجية بقبلي','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '152','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بباجة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '153','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بالقصرين','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '154','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية في المواصلات بتونس','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '155','university_id' => '36','ar_name' => 'المعهد العالي للدراسات التكنولوجية بقليبية','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES TECHNOLOGIQUES ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '156','university_id' => '37','ar_name' => 'المعهد العالي للغات المطبقة بالمكنين','fr_name' => 'INSTITUT SUPERIEUR DES LANGUES APPLIQUEES DE ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '157','university_id' => '37','ar_name' => 'كلية العلوم بالمنستير','fr_name' => 'FACULTE DES SCIENCES DE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '158','university_id' => '37','ar_name' => 'المعهد التحضيري للدراسات الهندسية بالمنستير','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '159','university_id' => '37','ar_name' => 'المعهد العالي للبيوتكنولوجيا بالمنستير','fr_name' => 'INSTITUT SUPERIEUR DE BIOTECHNOLOGIE DE MONAS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '160','university_id' => '37','ar_name' => 'المعهد العالي لمهن الموضة بالمنستير','fr_name' => 'INSTITUT SUPERIEUR DE LA MODE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '161','university_id' => '37','ar_name' => 'المعهد العالي للإعلامية بالمهدية','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE DE MAHDIA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '162','university_id' => '37','ar_name' => 'كلية الطب بالمنستير','fr_name' => 'FACULTE DE MEDECINE DE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '163','university_id' => '37','ar_name' => 'المدرسة الوطنية للمهندسين بالمنستير','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '164','university_id' => '37','ar_name' => 'المعهد العالي للإعلامية والرياضيات بالمنستير','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE & DE MATHEM','created_at' => NULL,'updated_at' => NULL),
            array('id' => '165','university_id' => '37','ar_name' => 'المعهد العالي للدراسات التطبيقية في الانسانيات بالمهدية','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '166','university_id' => '37','ar_name' => 'المعهد العالي للفنون والحرف بالمهدية','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE MAHD','created_at' => NULL,'updated_at' => NULL),
            array('id' => '167','university_id' => '37','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بالمهدية','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '168','university_id' => '37','ar_name' => 'المدرسة العليا لعلوم وتقنيات الصحة بالمنستير','fr_name' => 'ECOLE SUPERIEURE DES SCIENCES & TECHNIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '169','university_id' => '37','ar_name' => 'كلية طب الأسنان بالمنستير','fr_name' => 'FACULTE DE MEDECINE DENTAIRE DE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '170','university_id' => '37','ar_name' => 'كلية العلوم الإقتصادية والتصرف بالمهدية','fr_name' => 'FACULTE DES SCIENCES ECONOMIQUES & DE GESTION','created_at' => NULL,'updated_at' => NULL),
            array('id' => '171','university_id' => '37','ar_name' => 'كلية الصيدلة بالمنستير','fr_name' => 'FACULTE DE PHARMACIE DE MONASTIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '172','university_id' => '38','ar_name' => 'المعهد العالي للفنون والحرف بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE KAIR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '173','university_id' => '38','ar_name' => 'المعهد العالي للدراسات القانونية والسياسية بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES JURIDIQUES ET  ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '174','university_id' => '38','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '175','university_id' => '38','ar_name' => 'المعهد العالي للفنون والحرف بسيدي بوزيد','fr_name' => 'INSTITUT SUPERIEUR DES ARTS ET METIERS DE SID','created_at' => NULL,'updated_at' => NULL),
            array('id' => '176','university_id' => '38','ar_name' => 'كلية الآداب والعلوم الإنسانية بالقيروان','fr_name' => 'FACULTE DES LETTRES & DES SCIENCES HUMAINES D','created_at' => NULL,'updated_at' => NULL),
            array('id' => '177','university_id' => '38','ar_name' => 'المعهد التحضيري للدراسات الهندسية بالقيروان','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '178','university_id' => '38','ar_name' => 'المعهد العالي للدراسات التطبيقية في الانسانيات بسبيطلة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '179','university_id' => '38','ar_name' => 'المعهد العالي للفنون والحرف بالقصرين','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE KASS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '180','university_id' => '38','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بالقصرين','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '181','university_id' => '38','ar_name' => 'كلية العلوم والتقنيات يسيدي بوزيد','fr_name' => 'FACULTE DES SCIENCES ET TECHNIQUES SIDI BOUZI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '182','university_id' => '38','ar_name' => 'المعهد العالي للإعلامية والتصرف بالقيروان','fr_name' => 'INSTITUT SUPERIEUR D\'INFORMATIQUE & DE GESTIO','created_at' => NULL,'updated_at' => NULL),
            array('id' => '183','university_id' => '38','ar_name' => 'المعهد العالي للرياضيات التطبيقية والإعلامية بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DE MATHEMATIQUES APPLIQUEE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '184','university_id' => '39','ar_name' => 'المعهد العالي للدراسات التطبيقية في الإنسانيات بقفصة','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '185','university_id' => '39','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بقفصة','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '186','university_id' => '39','ar_name' => 'المعهد العالي لعلوم وتكنولوجيا الطاقة بقفصة','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES & TECHNOLOGIE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '187','university_id' => '39','ar_name' => 'المعهد العالي للرياضة والتربية البدنية بقفصة','fr_name' => 'INSTITUT SUPERIEUR DU SPORT & DE L\'EDUCATION ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '188','university_id' => '39','ar_name' => 'المعهد العالي لإدارة المؤسسات بقفصة','fr_name' => 'INSTITUT SUPERIEUR  D\'ADMINISTRATION DES ENTR','created_at' => NULL,'updated_at' => NULL),
            array('id' => '189','university_id' => '39','ar_name' => 'المعهد العالي للفنون والحرف بقفصة','fr_name' => 'INSTITUT SUPERIEUR DES ARTS & METIERS DE GAFS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '190','university_id' => '39','ar_name' => 'المعهد العالي للدراسات التطبيقية في الإنسانيات بتوزر','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '191','university_id' => '39','ar_name' => 'كلية العلوم بقفصة','fr_name' => 'FACULTE DES  SCIENCES DE GAFSA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '192','university_id' => '39','ar_name' => 'المدرسة الوطنية للمهندسين بقفصة','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE GAFSA','created_at' => NULL,'updated_at' => NULL),
            array('id' => '193','university_id' => '39','ar_name' => 'المعهد التحضيري للدراسات الهندسية بقفصة','fr_name' => 'INSTITUT PREPARATOIRE AUX ETUDES D\'INGENIEURS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '194','university_id' => '35','ar_name' => 'المعهد العالي للعلوم التطبيقية والتكنولوجيا بقابس','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES APPLIQUEES & ','created_at' => NULL,'updated_at' => NULL),
            array('id' => '195','university_id' => '285','ar_name' => 'المعهد العالي للتربية والتكوين المستمر','fr_name' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '196','university_id' => '27','ar_name' => 'المعهد العالي للدراسات التطبيقية في الإنسانيات بزغوان','fr_name' => 'INSTITUT SUPERIEUR DES ETUDES APPLIQUEES EN H','created_at' => NULL,'updated_at' => NULL),
            array('id' => '197','university_id' => '28','ar_name' => 'المعهد العالي لتاريخ تونس المعاصر','fr_name' => 'INSTITUT SUPERIEUR DE L\'HISTOIRE  DE LA TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '198','university_id' => '29','ar_name' => 'المدرسة الوطنية للمهندسين بتونس','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE TUNIS','created_at' => NULL,'updated_at' => NULL),
            array('id' => '199','university_id' => '30','ar_name' => 'المدرسة الوطنية للهندسة المعمارية والتعمير بتونس','fr_name' => 'ECOLE  NATIONALE  D\'ARCHITECTURE & D\'URBANISM','created_at' => NULL,'updated_at' => NULL),
            array('id' => '200','university_id' => '30','ar_name' => '	المدرسة الوطنية للمهندسين بقرطاج','fr_name' => 'ECOLE NATIONALE D\'INGENIEURS DE CARTHAGE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '201','university_id' => '31','ar_name' => 'المعهد العالي للعلوم الإسلامية بالقيروان','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES ISLAMIQUE KAI','created_at' => NULL,'updated_at' => NULL),
            array('id' => '202','university_id' => '32','ar_name' => 'كلية الحقوق والعلوم السياسية بسوسة','fr_name' => 'FACULTE DE DROIT & DES SCIENCES POLITIQUES DE','created_at' => NULL,'updated_at' => NULL),
            array('id' => '203','university_id' => '33','ar_name' => 'المدرسة الوطنية للإلكترونيك والإتصالات بصفاقس','fr_name' => 'ECOLE NATIONALE D\'ELECTRONIQUE ET DES TELECOM','created_at' => NULL,'updated_at' => NULL),
            array('id' => '204','university_id' => '34','ar_name' => 'المعهد العالي للعلوم الإنسانية بجندوبة','fr_name' => 'INSTITUT SUPERIEUR DES SCIENCES HUMAINES DE J','created_at' => NULL,'updated_at' => NULL),
            array('id' => '205','university_id' => '34','ar_name' => 'المدرسة العليا للمهندسين بمجاز الباب','fr_name' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '206','university_id' => '27','ar_name' => 'دار المعلمين العليا','fr_name' => NULL,'created_at' => NULL,'updated_at' => NULL),
            array('id' => '214','university_id' => '27','ar_name' => 'المعهد التحضيري للدراسات الأدبية والعلوم الإنسانية بتونس','fr_name' => 'INSTITUT PREPARATOIRE DES ETUDES LITTERAIRES ','created_at' => NULL,'updated_at' => NULL)
          );
          DB::table('establishments')->insert($establishments);
    }
}
